default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: page-content-api-db-dev

test:
  <<: *default
  database: page-content-api-db-test

production:
  <<: *default
  database: page-content-api-db-prod
